<?php

namespace Database\Seeders;

use App\Models\Job;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $jobs = [
            [
                'title' => 'Junior UI/UX Designer',
                'company' => 'Tokopedia',
                'location' => 'Jakarta - Hybrid',
                'type' => 'fulltime',
                'work_mode' => 'hybrid',
                'description' => 'Mendesain wireframe, prototype, dan melakukan user research untuk fitur e-commerce. Kolaborasi erat dengan tim product dan engineering.',
                'required_skills' => ['Figma', 'User Research', 'Prototyping', 'Design System'],
                'salary_range' => 'Rp 6.000.000 - 9.000.000',
                'posted_at' => now()->subDays(2),
            ],
            [
                'title' => 'Product Designer',
                'company' => 'Ruangguru',
                'location' => 'Remote',
                'type' => 'fulltime',
                'work_mode' => 'remote',
                'description' => 'Merancang pengalaman belajar digital untuk jutaan siswa. Membutuhkan pemahaman kuat tentang design thinking dan riset pengguna.',
                'required_skills' => ['Figma', 'Design Thinking', 'User Research', 'Wireframing'],
                'salary_range' => 'Rp 7.000.000 - 10.000.000',
                'posted_at' => now()->subDays(4),
            ],
            [
                'title' => 'UX Researcher Intern',
                'company' => 'Kata.ai',
                'location' => 'Bandung',
                'type' => 'internship',
                'work_mode' => 'onsite',
                'description' => 'Membantu tim UX melakukan riset pengguna untuk produk chatbot AI, termasuk usability testing dan analisis data kualitatif.',
                'required_skills' => ['User Research', 'Usability Testing', 'Data Analysis'],
                'salary_range' => 'Rp 2.500.000 - 3.500.000',
                'posted_at' => now()->subDays(6),
            ],
            [
                'title' => 'UI Designer',
                'company' => 'Dana',
                'location' => 'Jakarta',
                'type' => 'contract',
                'work_mode' => 'onsite',
                'description' => 'Mendesain antarmuka aplikasi fintech dengan standar keamanan dan kemudahan penggunaan tinggi.',
                'required_skills' => ['Figma', 'Design System', 'Mobile Design'],
                'salary_range' => 'Rp 8.000.000 - 12.000.000',
                'posted_at' => now()->subDays(8),
            ],
            [
                'title' => 'Design System Intern',
                'company' => 'Gojek',
                'location' => 'Remote',
                'type' => 'internship',
                'work_mode' => 'remote',
                'description' => 'Membantu tim design system mengelola komponen UI yang konsisten lintas produk Gojek.',
                'required_skills' => ['Figma', 'Design System', 'Component Library'],
                'salary_range' => 'Rp 2.000.000 - 3.000.000',
                'posted_at' => now()->subDays(10),
            ],
            [
                'title' => 'Junior Product Designer',
                'company' => 'Bibit',
                'location' => 'Jakarta',
                'type' => 'fulltime',
                'work_mode' => 'hybrid',
                'description' => 'Bergabung dengan tim product untuk merancang pengalaman investasi yang mudah dipahami pemula.',
                'required_skills' => ['Figma', 'User Research', 'Prototyping'],
                'salary_range' => 'Rp 6.500.000 - 9.500.000',
                'posted_at' => now()->subDays(1),
            ],
            [
                'title' => 'Frontend Developer',
                'company' => 'Traveloka',
                'location' => 'Jakarta - Hybrid',
                'type' => 'fulltime',
                'work_mode' => 'hybrid',
                'description' => 'Membangun antarmuka web menggunakan React.js dan TypeScript untuk platform travel booking.',
                'required_skills' => ['React', 'TypeScript', 'JavaScript', 'CSS'],
                'salary_range' => 'Rp 9.000.000 - 14.000.000',
                'posted_at' => now()->subDays(3),
            ],
            [
                'title' => 'Backend Engineer',
                'company' => 'Ajaib',
                'location' => 'Remote',
                'type' => 'fulltime',
                'work_mode' => 'remote',
                'description' => 'Mengembangkan API dan sistem backend untuk platform investasi saham dan reksadana.',
                'required_skills' => ['PHP', 'Laravel', 'MySQL', 'REST API'],
                'salary_range' => 'Rp 10.000.000 - 15.000.000',
                'posted_at' => now()->subDays(5),
            ],
            [
                'title' => 'Data Analyst Intern',
                'company' => 'Blibli',
                'location' => 'Jakarta',
                'type' => 'internship',
                'work_mode' => 'onsite',
                'description' => 'Menganalisis data transaksi dan perilaku pengguna untuk mendukung keputusan bisnis tim marketing.',
                'required_skills' => ['SQL', 'Python', 'Data Analysis', 'Excel'],
                'salary_range' => 'Rp 2.500.000 - 3.500.000',
                'posted_at' => now()->subDays(7),
            ],
            [
                'title' => 'Mobile Developer (React Native)',
                'company' => 'Halodoc',
                'location' => 'Jakarta - Hybrid',
                'type' => 'fulltime',
                'work_mode' => 'hybrid',
                'description' => 'Mengembangkan fitur baru pada aplikasi mobile kesehatan digital menggunakan React Native.',
                'required_skills' => ['React Native', 'JavaScript', 'REST API'],
                'salary_range' => 'Rp 9.500.000 - 13.000.000',
                'posted_at' => now()->subDays(9),
            ],
            [
                'title' => 'QA Engineer',
                'company' => 'Sicepat',
                'location' => 'Bandung',
                'type' => 'fulltime',
                'work_mode' => 'onsite',
                'description' => 'Melakukan manual dan automation testing untuk sistem logistik dan tracking pengiriman.',
                'required_skills' => ['Manual Testing', 'Automation Testing', 'SQL'],
                'salary_range' => 'Rp 6.000.000 - 9.000.000',
                'posted_at' => now()->subDays(11),
            ],
            [
                'title' => 'Business Analyst',
                'company' => 'OVO',
                'location' => 'Jakarta',
                'type' => 'fulltime',
                'work_mode' => 'hybrid',
                'description' => 'Menjembatani kebutuhan bisnis dan tim teknis untuk pengembangan fitur pembayaran digital.',
                'required_skills' => ['Data Analysis', 'SQL', 'Business Process'],
                'salary_range' => 'Rp 8.000.000 - 11.000.000',
                'posted_at' => now()->subDays(12),
            ],
            [
                'title' => 'Content Writer Intern',
                'company' => 'Zenius',
                'location' => 'Remote',
                'type' => 'internship',
                'work_mode' => 'remote',
                'description' => 'Menulis konten edukatif untuk platform belajar online, termasuk artikel dan skrip video.',
                'required_skills' => ['Copywriting', 'SEO', 'Content Strategy'],
                'salary_range' => 'Rp 2.000.000 - 3.000.000',
                'posted_at' => now()->subDays(13),
            ],
            [
                'title' => 'DevOps Engineer',
                'company' => 'Xendit',
                'location' => 'Remote',
                'type' => 'fulltime',
                'work_mode' => 'remote',
                'description' => 'Mengelola infrastruktur cloud dan CI/CD pipeline untuk sistem pembayaran skala besar.',
                'required_skills' => ['Docker', 'Kubernetes', 'CI/CD', 'AWS'],
                'salary_range' => 'Rp 12.000.000 - 18.000.000',
                'posted_at' => now()->subDays(14),
            ],
            [
                'title' => 'Graphic Design Intern',
                'company' => 'Kredivo',
                'location' => 'Jakarta',
                'type' => 'internship',
                'work_mode' => 'onsite',
                'description' => 'Membuat aset visual untuk kebutuhan marketing dan sosial media perusahaan fintech.',
                'required_skills' => ['Figma', 'Adobe Illustrator', 'Visual Design'],
                'salary_range' => 'Rp 2.200.000 - 3.200.000',
                'posted_at' => now()->subDays(15),
            ],
        ];

        foreach ($jobs as $job) {
            Job::create($job);
        }
    }
}